#!/usr/bin/env bash
set -euo pipefail

LLM_MODEL="${LLM_MODEL:-llama3.2:3b}"
BASE_BRANCH="${BASE_BRANCH:-main}"
# defaults if metadata generation fails
DEFAULT_COMMIT_MESSAGE="${COMMIT_MESSAGE:-chore(llm): apply local LLM suggestions}"
DEFAULT_PR_TITLE="${PR_TITLE_PREFIX:-LLM suggestions}: ${BASE_BRANCH}"

: "${GITHUB_OUTPUT:=${GITHUB_OUTPUT:-/tmp/github_output}}"
touch "$GITHUB_OUTPUT"

# 1) Short-circuit when no changes
if grep -qx 'NO_CHANGES' .llm_raw.txt; then
  echo "no_changes=true" >> "$GITHUB_OUTPUT"
  exit 0
fi

# 2) Extract unified diff
awk '/^---\s+a\//,0' .llm_raw.txt > .llm_patch.diff || true
if ! grep -q '^--- a/' .llm_patch.diff; then
  echo "Model did not return a valid unified diff. Skipping."
  echo "no_changes=true" >> "$GITHUB_OUTPUT"
  exit 0
fi

# 3) Dry-run apply
if ! patch -p0 --dry-run < .llm_patch.diff ; then
  echo "Patch failed to apply cleanly. Skipping."
  echo "no_changes=true" >> "$GITHUB_OUTPUT"
  exit 0
fi

# 4) Generate PR/commit metadata with the local model
python .github/scripts/llm_metadata.py || true

# 5) Read metadata (fallbacks if absent/invalid)
PR_TITLE="${DEFAULT_PR_TITLE}"
COMMIT_MESSAGE="${DEFAULT_COMMIT_MESSAGE}"
PR_BODY="Automated suggestions generated by a **fully local LLM** via Ollama (\`${LLM_MODEL}\`)."

if [[ -f ".llm_meta.json" ]]; then
  if jq -e . >/dev/null 2>&1 < .llm_meta.json; then
    PR_TITLE="$(jq -r '.title // empty' .llm_meta.json || echo "$PR_TITLE")"
    COMMIT_MESSAGE="$(jq -r '.commit_message // empty' .llm_meta.json || echo "$COMMIT_MESSAGE")"
    META_BODY="$(jq -r '.body // empty' .llm_meta.json || true)"
    if [[ -n "$META_BODY" ]]; then
      PR_BODY="$META_BODY"
    fi
  fi
fi

# 6) Apply, branch, commit, push
patch -p0 < .llm_patch.diff

SHORTSHA=$(git rev-parse --short HEAD)
DATESTR=$(date -u +%Y%m%d-%H%M%S)
BOT_BRANCH="llm/suggest-${DATESTR}-${SHORTSHA}"

git checkout -b "${BOT_BRANCH}"
git add -A
if git diff --cached --quiet; then
  echo "Nothing to commit after applying patch."
  echo "no_changes=true" >> "$GITHUB_OUTPUT"
  exit 0
fi

git -c user.name="github-actions[bot]" \
    -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit -m "${COMMIT_MESSAGE}"
git push -u origin "${BOT_BRANCH}"

# 7) Compose body (include diff in collapsible details)
{
  echo "$PR_BODY"
  echo
  echo "<details><summary>Unified diff applied</summary>"
  echo
  echo '```diff'
  sed -n '1,400p' .llm_patch.diff
  echo '```'
  echo "</details>"
} > .llm_body.md

# 8) Open PR
gh pr create \
  --title "${PR_TITLE}" \
  --body-file .llm_body.md \
  --base "${BASE_BRANCH}" \
  --head "${BOT_BRANCH}"

echo "no_changes=false" >> "$GITHUB_OUTPUT"
