name: AutoRefactor (CLI) PR

on:
  workflow_dispatch:
    inputs:
      project_file:
        description: "Path to Eclipse .project file (e.g., ./.project or ./eclipse/.project)"
        required: true
        default: ".project"
      exclude_refactorings:
        description: "Comma-separated list to EXCLUDE (optional)"
        required: false
        default: ""
      path_filter:
        description: "Only refactor files whose path contains this string (optional)"
        required: false
        default: ""
      path_re:
        description: "Java regex to select files (optional; defaults to '.*' if empty)"
        required: false
        default: ""
      source_dirs:
        description: "Repeatable source dirs to target (optional). Use newline to add multiple, e.g. 'src/main/java\\nsrc/test/java'"
        required: false
        default: ""
      source_level:
        description: "Java source level (e.g., 8, 11, 17) — optional"
        required: false
        default: "8"
      classpath_vars:
        description: "Classpath variables (optional), one per line as KEY=/abs/path"
        required: false
        default: ""
      eclipse_url:
        description: "Eclipse tar.gz URL (Linux x86_64). Override if needed."
        required: false
        default: "https://archive.eclipse.org/technology/epp/downloads/release/oxygen/R/eclipse-java-oxygen-R-linux-gtk-x86_64.tar.gz"
      eclipse_cmd_name:
        description: "Command name the wrapper will call via AUTOREFACTOR_ECLIPSE"
        required: false
        default: "eclipse-oxygen-vanilla"

permissions:
  contents: write
  pull-requests: write

jobs:
  autorefactor:
    name: Run AutoRefactor (ALL refactorings) and open PR
    runs-on: ubuntu-latest
    env:
      # Make Eclipse instance discoverable by the wrapper script
      AUTOREFACTOR_ECLIPSE: ${{ inputs.eclipse_cmd_name }}

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout AutoRefactorCli tool
        uses: actions/checkout@v4
        with:
          repository: cal101/AutoRefactorCli
          path: tools/AutoRefactorCli
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven

      - name: Download & install Eclipse (headless)
        shell: bash
        run: |
          set -euo pipefail
          cd "$RUNNER_TEMP"
          echo "Downloading Eclipse from: ${{ inputs.eclipse_url }}"
          curl -fL -o eclipse.tar.gz "${{ inputs.eclipse_url }}"
          tar -xzf eclipse.tar.gz
          # Find extracted dir (starts with 'eclipse')
          ECLIPSE_DIR="$(find . -maxdepth 1 -type d -name 'eclipse*' | head -n1)"
          if [[ -z "$ECLIPSE_DIR" || ! -x "$ECLIPSE_DIR/eclipse" ]]; then
            echo "::error::Could not locate Eclipse executable after extraction."
            exit 1
          fi
          sudo ln -s "$PWD/$ECLIPSE_DIR/eclipse" "/usr/local/bin/${{ inputs.eclipse_cmd_name }}"
          which "${{ inputs.eclipse_cmd_name }}"
          "${{ inputs.eclipse_cmd_name }}" -nosplash -application org.eclipse.equinox.p2.director -help >/dev/null 2>&1 || true

      - name: Patch versions (pom.xml, MANIFEST.MF, build-cli)
        working-directory: tools/AutoRefactorCli
        shell: bash
        run: |
          set -euo pipefail

          echo ">> Before patch:"
          grep '<version>' cli/pom.xml || true
          grep '^Bundle-Version' cli/META-INF/MANIFEST.MF || true
          grep 'org\.autorefactor\.plugin-.*SNAPSHOT\.jar' build-cli || true
          grep 'org\.autorefactor\.cli-.*SNAPSHOT\.jar' build-cli || true

          # 1) pom.xml: 2.0.0-SNAPSHOT -> 1.2.0-SNAPSHOT
          sed -i 's|<version>2\.0\.0-SNAPSHOT</version>|<version>1.2.0-SNAPSHOT</version>|g' cli/pom.xml
          # 2) MANIFEST.MF: 2.0.0 -> 1.2.0
          sed -i 's|^Bundle-Version:\s*2\.0\.0$|Bundle-Version: 1.2.0|g' cli/META-INF/MANIFEST.MF
          # 3) build-cli: copy correct jar names
          sed -i 's|org\.autorefactor\.plugin-2\.0\.0-SNAPSHOT\.jar|org.autorefactor.plugin-1.2.0-SNAPSHOT.jar|g' build-cli
          sed -i 's|org\.autorefactor\.cli-2\.0\.0-SNAPSHOT\.jar|org.autorefactor.cli-1.2.0-SNAPSHOT.jar|g' build-cli

          echo ">> After patch:"
          grep '<version>' cli/pom.xml || true
          grep '^Bundle-Version' cli/META-INF/MANIFEST.MF || true
          grep 'org\.autorefactor\.plugin-.*SNAPSHOT\.jar' build-cli || true
          grep 'org\.autorefactor\.cli-.*SNAPSHOT\.jar' build-cli || true

      - name: Build AutoRefactorCli (Linux)
        working-directory: tools/AutoRefactorCli
        run: |
          chmod +x ./build-cli
          ./build-cli
          ls -la ./cli/target/autorefactor/bin

      - name: Collect ALL refactorings from CLI
        id: collect
        shell: bash
        run: |
          set -euo pipefail
          BIN="tools/AutoRefactorCli/cli/target/autorefactor/bin/autorefactor"

          # Gather names before " - " from list output
          mapfile -t NAMES < <("$BIN" list | awk -F' - ' '/Refactoring/ {gsub(/^[[:space:]]+/, "", $1); print $1}')
          if [[ ${#NAMES[@]} -eq 0 ]]; then
            echo "::error title=No refactorings found::Could not parse any refactoring names from 'autorefactor list'."
            exit 1
          fi
          REFS=$(IFS=, ; echo "${NAMES[*]}")
          echo "refactorings=$REFS" >> "$GITHUB_OUTPUT"
          printf '%s' "$REFS" > /tmp/all_refactorings.txt

      - name: Prepare AutoRefactor arguments (apply ALL)
        id: args
        shell: bash
        run: |
          set -euo pipefail
          PROJECT_FILE="${{ inputs.project_file }}"
          EXCLUDE="${{ inputs.exclude_refactorings }}"
          PATH_FILTER="${{ inputs.path_filter }}"
          PATH_RE="${{ inputs.path_re }}"
          SOURCE_DIRS_RAW="${{ inputs.source_dirs }}"
          SOURCE_LEVEL="${{ inputs.source_level }}"
          CLASSPATH_VARS_RAW="${{ inputs.classpath_vars }}"
          REFACTORINGS="$(cat /tmp/all_refactorings.txt)"

          if [[ ! -f "$PROJECT_FILE" ]]; then
            echo "::error file=$PROJECT_FILE,title=.project not found::The specified Eclipse project file was not found."
            exit 1
          fi

          declare -a ARGS
          ARGS+=(apply --project "$PROJECT_FILE" --refactorings "$REFACTORINGS")
          [[ -n "$EXCLUDE" ]] && ARGS+=(--exclude-refactorings "$EXCLUDE")
          [[ -n "$PATH_FILTER" ]] && ARGS+=(--path-filter "$PATH_FILTER")
          [[ -n "$PATH_RE" ]] && ARGS+=(--path-re "$PATH_RE")
          [[ -n "$SOURCE_LEVEL" ]] && ARGS+=(--source-level "$SOURCE_LEVEL")

          if [[ -n "$SOURCE_DIRS_RAW" ]]; then
            while IFS= read -r line; do
              [[ -z "$line" ]] && continue
              ARGS+=(--source "$line")
            done <<< "$SOURCE_DIRS_RAW"
          fi

          if [[ -n "$CLASSPATH_VARS_RAW" ]]; then
            while IFS= read -r kv; do
              [[ -z "$kv" ]] && continue
              # README shows: --classpath-variable key=value
              ARGS+=(--classpath-variable "$kv")
            done <<< "$CLASSPATH_VARS_RAW"
          fi

          printf '%s\0' "${ARGS[@]}" > /tmp/autorefactor.args
          echo "rendered=$(printf '%q ' autorefactor "${ARGS[@]}")" >> "$GITHUB_OUTPUT"

      - name: Apply refactorings (ALL)
        shell: bash
        env:
          AUTOREFACTOR_ECLIPSE: ${{ inputs.eclipse_cmd_name }}
        run: |
          set -euo pipefail
          mapfile -d '' ARGS < /tmp/autorefactor.args
          BIN="tools/AutoRefactorCli/cli/target/autorefactor/bin/autorefactor"
          echo "Using Eclipse: $AUTOREFACTOR_ECLIPSE"
          echo "Running: $BIN ${ARGS[*]@Q}"
          "$BIN" "${ARGS[@]}"

      - name: Show diff (for logs)
        run: |
          git status
          git --no-pager diff --name-only

      - name: Create PR with changes
        if: ${{ !cancelled() }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(refactor): apply AutoRefactorCli (ALL refactorings)
          title: "Apply AutoRefactorCli (ALL) — ${{ github.ref_name }}"
          body: |
            This PR was generated by **AutoRefactorCli** on JDK 8, applying *all* available refactorings.

            Eclipse: `${{ inputs.eclipse_cmd_name }}` from `${{ inputs.eclipse_url }}`
            Patched to build against 1.2.0:
            - `cli/pom.xml`: `2.0.0-SNAPSHOT` → `1.2.0-SNAPSHOT`
            - `cli/META-INF/MANIFEST.MF`: `2.0.0` → `1.2.0`
            - `build-cli`: copies `-1.2.0-SNAPSHOT.jar` artifacts
          branch: "autorefactor/cli-all-${{ github.run_id }}"
          delete-branch: true
          add-paths: |
            **/*
